### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException - getCatFile(CatalogList.java:234)

### ISSUE THREAD

**Issue by Utyff** [Utyff/pMetro#14]
Last reported Today, 5:09 AM
Reports this week 1
Reports total 1
Application version  110  1
Android version   Android 4.4  1
Device    Xperia™ E4 (E2105) 1 

java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
    at java.util.ArrayList.get(ArrayList.java:310)
    at com.utyf.pmetro.settings.CatalogList.getCatFile(CatalogList.java:234)
    at com.utyf.pmetro.settings.CatalogManagement.onCreateContextMenu(CatalogManagement.java:184)
    at android.view.View.createContextMenu(View.java:8577)
    at com.android.internal.view.menu.ContextMenuBuilder.show(ContextMenuBuilder.java:81)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.showContextMenuForChild(PhoneWindow.java:2406)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:682)
    at android.widget.AbsListView.performLongPress(AbsListView.java:3101)
    at android.widget.AbsListView$CheckForLongPress.run(AbsListView.java:3045)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5398)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by asdzxcasd** [comment]
Я сделал открытие карты сразу по нажатию. Заодно исправил эту ошибку. 
https://github.com/Utyff/pMetro/commit/6403766a8a2f4aec1e7a137488d66397585e5094

**Comment by Utyff** [comment]
Странно. Я не смог повторить этот баг.
Пробовал разные версии Android.
У меня onCreateContextMenu не вызывается при нажатии на групповой элемент.

**Comment by asdzxcasd** [comment]
У меня баг воспроизводился при долгом нажатии, потому что при создании класса вызывается `registerForContextMenu(elvCat)`

**Comment by Utyff** [comment]
Да, так получаю ошибку.
