### ISSUE TITLE
Приложение падает с ошибкой Unable to start activity ComponentInfo{com.utyf.pmetro/com.utyf.pmetro.map.StationInfoActivity}: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4

### ISSUE THREAD

**Issue by RockBomber** [Utyff/pMetro#19]
Приложение падает с ошибкой  `Unable to start activity ComponentInfo{com.utyf.pmetro/com.utyf.pmetro.map.StationInfoActivity}: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4` при открытии информации о некоторых станциях (по двойному клику).
Например, при открытии информации о Маяквоской такая ошибка в Logcat:

```
03-09 15:50:27.025 11113-11113/com.utyf.pmetro E/VEC_SpotRect /16: Wrong parameters.  <609, 608, 30, 30>  
03-09 15:50:27.035 11113-11113/com.utyf.pmetro D/AndroidRuntime: Shutting down VM
03-09 15:50:27.035 11113-11113/com.utyf.pmetro E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.utyf.pmetro, PID: 11113
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.utyf.pmetro/com.utyf.pmetro.map.StationInfoActivity}: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                  Caused by: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
                                                                     at com.utyf.pmetro.map.vec.VEC_Element_SpotRect.<init>(VEC_Element_SpotRect.java:29)
                                                                     at com.utyf.pmetro.map.vec.VEC.loadVEC(VEC.java:114)
                                                                     at com.utyf.pmetro.map.vec.VEC.load(VEC.java:48)
                                                                     at com.utyf.pmetro.map.StationData.load(StationData.java:55)
                                                                     at com.utyf.pmetro.map.StationInfoActivity.onCreate(StationInfoActivity.java:54)
                                                                     at android.app.Activity.performCreate(Activity.java:6876)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:158) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
03-09 15:50:36.075 11113-11113/com.utyf.pmetro I/Process: Sending signal. PID: 11113 SIG: 9
```

Часть содержимого файла `Mayakovskaya.vec` на котором происходит падение:
```
; Выходы
Angle 50
PenColor FFD900
BrushColor 615F56
SpotRect 167, 163, 30, 30, ShowMessage Выход №1
SpotRect 609, 608, 30, 30
SpotRect 672, 743, 30, 30
SpotRect 316, 876, 30, 30
BrushColor -1
TextOut Arial, 25, 175, 164, 1
TextOut Arial, 25, 617, 609, 2
TextOut Arial, 25, 680, 744, 3
TextOut Arial, 25, 324, 877, 4
```

Файл `Mayakovskaya.vec` брал из инсталлятора `pMetroSetup.exe` от 04.03.2018

Судя по всему приложение ожидает, что SpotRect должен содержать название или номер выхода, но в некоторых `vec` файлах эта информация отсутствует. Возможно стоит сделать обработку этой ситуации, и например просто подставляя пустую строку вместо информации о названии или номере выхода?

**Comment by RockBomber** [comment]
С таким корявеньким конечно патчем открывает информацию о станциях без ошибок:

```diff
diff --git a/app/src/main/java/com/utyf/pmetro/map/vec/VEC_Element_SpotRect.java b/app/src/main/java/com/utyf/pmetro/map/vec/VEC_Element_SpotRect.java
index cee0334..a2f4e3f 100644
--- a/app/src/main/java/com/utyf/pmetro/map/vec/VEC_Element_SpotRect.java
+++ b/app/src/main/java/com/utyf/pmetro/map/vec/VEC_Element_SpotRect.java
@@ -6,6 +6,9 @@ import android.util.Log;
 
 import com.utyf.pmetro.util.ExtInteger;
 
+import java.util.ArrayList;
+import java.util.Arrays;
+
 
 public class VEC_Element_SpotRect extends VEC_Element {
     float   x,y,w,h;
@@ -16,6 +19,12 @@ public class VEC_Element_SpotRect extends VEC_Element {
         super(vv);
 
         String[] strs=param.split(",");
+        if (strs.length == 4) {
+            ArrayList<String> strsa = new ArrayList<>(Arrays.asList(strs));
+            strsa.add("");
+            strs = new String[ strsa.size() ];
+            strsa.toArray(strs);
+        }
         if( strs.length < 5 )  Log.e("VEC_SpotRect /16", "Wrong parameters.  <" + param + ">  ");
 
         x2 = ExtInteger.parseInt(strs[0]);
```

**Comment by dimqua** [comment]
Разве это не было исправлено в последних версиях карт?

**Comment by RockBomber** [comment]
Вместе с `pMetroSetup.exe` от 04.03.2018 идут карты `Moscow.pmz` с новой веткой метро от Делового центра до Петровского парка, которой нету среди карт выложенных на `https://pmetro.github.io/`
Но при их использовании возникает такой баг.

**Comment by Utyff** [comment]
Сейчас на github карты от 8 фев.
С последними картами андроид версия вылетает. Я посмотрю.

**Comment by Utyff** [comment]
Исправил
