### ISSUE TITLE
Не работает загрузка карт через https

### ISSUE THREAD

**Issue by asdzxcasd** [Utyff/pMetro#20]
После того, как карты стали загружаться через https, не удаётся подключиться к серверу на устройствах с API 15-19. Сервер на pmetro.github.io поддерживает протокол шифрования не ниже TLSv1.2, а в API 16-19 по умолчанию используется устаревший протокол SSLv3. Но эти устройства поддерживают TLSv1.2, и его можно включить. А вот как решить проблему для API 15 - непонятно, потому что на них TLSv1.2 нет в принципе. Видимо придётся просить пользователя скачать карты вручную. Ну или вообще отказаться от поддержки API 15.

Вот, что выводится при попытке использовать TLSv1.1 или TLSv1.2 на API 15:
```
03-16 22:17:10.988 1783-1801/com.utyf.pmetro E/AndroidRuntime: FATAL EXCEPTION: Thread-83
                                                               java.lang.IllegalArgumentException: protocol TLSv1.1 is not supported
                                                                   at org.apache.harmony.xnet.provider.jsse.NativeCrypto.checkEnabledProtocols(NativeCrypto.java:390)
                                                                   at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.setEnabledProtocols(OpenSSLSocketImpl.java:788)
                                                                   at com.utyf.pmetro.settings.MyTLSSocketFactory.enableTLSOnSocket(DownloadFile.java:291)
                                                                   at com.utyf.pmetro.settings.MyTLSSocketFactory.createSocket(DownloadFile.java:266)
                                                                   at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:197)
                                                                   at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:477)
                                                                   at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:432)
                                                                   at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)
                                                                   at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)
                                                                   at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
                                                                   at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:164)
                                                                   at com.utyf.pmetro.settings.DownloadFile.download(DownloadFile.java:76)
                                                                   at com.utyf.pmetro.settings.DownloadFile.access$000(DownloadFile.java:38)
                                                                   at com.utyf.pmetro.settings.DownloadFile$1.run(DownloadFile.java:132)
                                                                   at java.lang.Thread.run(Thread.java:856)
```

Ещё есть вариант использовать [ProviderInstaller](https://developers.google.com/android/reference/com/google/android/gms/security/ProviderInstaller) для того, чтобы обновить протоколы шифрования на телефоне, но для этого придётся добавлять в зависимости Goolge Play Services, но я думаю, что это плохая идея, потому что приложение не будет работать, если у пользователя не установлены Google Play Services.

**Comment by dimqua** [comment]
Сейчас пользователей Android 4.0.х надо еще поискать, думаю подавляющее большинство пользователей приложения и не заметит, если откажетесь от поддержки API 15.

**Comment by Utyff** [comment]
По статистике google play, сейчас всего - 2 239 установок и из них - 26 на Android 4.0.
И не факт что они живы.
Давай откажемся от API-15.

**Comment by asdzxcasd** [comment]
> Давай откажемся от API-15.

Да, пожалуй пришло время.

Добавил исправления: #21
